version: "3.8"

services:
  api-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://admin:password@3.83.45.37:27017/test?authSource=admin
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
